CREATE TABLE IF NOT EXISTS `class` (
    `cid` INT AUTO_INCREMENT PRIMARY KEY,
    `cname` VARCHAR(32) CHARACTER SET utf8,
    `credit` INT,
    `dept` VARCHAR(14) CHARACTER SET utf8,
    `instructor` VARCHAR(7) CHARACTER SET utf8,
    `description` VARCHAR(161) CHARACTER SET utf8,
    `modality` VARCHAR(9) CHARACTER SET utf8,
    `seats` INT
);
INSERT INTO `class` VALUES (100,'Fundamental of Drawing',2,'Drawing','Smith','Grasp the basic concepts of drawing, the different types of pencils, line work and shading.','In-Person',15),
	(101,'Faces',3,'Drawing','Smith','Using concepts like proportions and anatomy, implement them into creating faces.','In-Person',15),
	(102,'Landscapes',3,'Drawing','Smith','With the help of perspectives and detail, be able to replicate and create beautiful scenaries. ','In-Person',15),
	(103,'Cartoons and Comics',4,'Drawing','Smith','Cartoons character design and the history that comes with it, along with how to let a story flow with the use of drawings and choice words. ','In-Person',15),
	(200,'Fundamental of Calligraphy',2,'Calligraphy','Jones','Grasp the basic concepts of calligraphy, learn about the different type of writing implements and how to effectivly use them and other tools. ','Online',25),
	(201,'Calligraphy Around the World',3,'Calligraphy','Jones','Take a trip around the world and learn about the cultural impact of the different writing styles and how it compares to others around the world. ','Online',25),
	(202,'Digital Calligraphy',3,'Calligraphy','Jones','Taking the concepts learned in fundamentals of calligraphy, and implementing them into the digital realm. ','Online',25),
	(203,'Formal Event Styling Calligraphy',4,'Calligraphy','Jones','Using the basic concepts previously learned and how to use the efficiently in the formal enviroment with invitations and cards. ','Online',25),
	(300,'Fundamentals of Painting',2,'Painting','White','Grasp the basics of painting with the different painting styles, different painting mediums, and the best brushes to use for the goal you are trying to achieve. ','In-Person',15),
	(301,'Basics of Arylic',3,'Painting','White','Arylic is a common painting medium with a quality of being able to dry fast, so learning how to use it efficiently to make your paintings stand out. ','In-Person',15),
	(302,'The Story Behind the Painting',3,'Painting','White','Become familar with the world most famous or unknown paintings and how they came to be. ','In-Person',15),
	(303,'Oil Painting Restoration',4,'Painting','White','ADVANCED CLASS!! Learning how restore worn oil paintings back to their originial state with chemicals and touch ups. ','In-Person',15),
	(400,'Fundamentals of Photography',2,'Photography','Stevens','Grasp the basic concepts of photography, learn how to properly use a camera with the basics of aperture, different lenses, and more. ','In-Person',15),
	(401,'Professional Photography',3,'Photography','Stevens','ADVANCED CLASS!! Taking the basic skills and ramping up to build stronger skills for those who would like to become professionals. ','In-Person',15),
	(402,'Photoshop and Lightroom ',3,'Photography','Stevens','Using photos you have taken learn about how to edit them in Photoshop and Lightroom.','In-Person',15),
	(403,'Film Development ',4,'Photography','Stevens','Focuses on traditional film photography, covering film development, darkroom techniques, and printing.','In-Person',15),
	(500,'Fundamentals of Graphic Design ',2,'Graphic Design','Brown','Grasp the basic concepts of graphic design with the use of layout, visual communication, and typography. ','Online',25),
	(501,'Logo and Social Media Design ',3,'Graphic Design','Brown','Building an online presence is important so learning the basics and how to convey a message with only an image. ','Online',25),
	(502,'Web Design Essentials ',3,'Graphic Design','Brown','Covers the essential techniques and tools to improve user expeience and interface designs. ','Online',25),
	(503,'Adobe Creative Mastering',4,'Graphic Design','Brown','Learn how to use all of the tools Adobe has to offer and how to implement them into your workflow. ','Online',25);
